import './App.css';
import { useEffect, useMemo, useState } from 'react';
import questions from './data/questions';
import translations from './locales/translations';

const icons = { overview: '◈', library: '⌕', categories: '◫', favorites: '♡', explore: '↗', copy: '▣', arrow: '→', spark: '✦' };

function App() {
  const [language, setLanguage] = useState(() => localStorage.getItem('hashquest-language') || 'en');
  const [view, setView] = useState('overview');
  const [favorites, setFavorites] = useState(() => JSON.parse(localStorage.getItem('hashquest-favorites') || '[]'));
  const [explored, setExplored] = useState(() => JSON.parse(localStorage.getItem('hashquest-explored') || '[]'));
  const [currentId, setCurrentId] = useState(2);
  const [search, setSearch] = useState('');
  const [difficulty, setDifficulty] = useState('all');
  const [copied, setCopied] = useState(false);
  const [showOnboarding, setShowOnboarding] = useState(() => !localStorage.getItem('hashquest-onboarded'));

  const t = translations[language];
  const current = questions.find((item) => item.id === currentId) || questions[0];
  const categories = [...new Set(questions.map((item) => item.category[language]))];

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('hashquest-language', language);
  }, [language]);
  useEffect(() => { localStorage.setItem('hashquest-favorites', JSON.stringify(favorites)); localStorage.setItem('hashquest-explored', JSON.stringify(explored)); }, [favorites, explored]);

  const markExplored = (id) => setExplored((items) => items.includes(id) ? items : [...items, id]);
  const selectQuestion = (id) => { setCurrentId(id); markExplored(id); setView('library'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const nextQuestion = () => { const pool = questions.filter((item) => item.id !== current.id); selectQuestion(pool[Math.floor(Math.random() * pool.length)].id); };
  const toggleFavorite = (id) => setFavorites((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const copyQuestion = async (item) => { await navigator.clipboard.writeText(item.question[language]); setCopied(true); setTimeout(() => setCopied(false), 1800); };
  const filteredQuestions = useMemo(() => questions.filter((item) => { const haystack = [item.question[language], item.category[language], item.topic, item.tags.join(' ')].join(' ').toLowerCase(); return haystack.includes(search.toLowerCase()) && (difficulty === 'all' || item.difficulty === difficulty) && (view !== 'favorites' || favorites.includes(item.id)); }), [language, search, difficulty, view, favorites]);
  const stats = [[t.stats.questions, questions.length, '01'], [t.stats.categories, categories.length, '02'], [t.stats.beginner, questions.filter((q) => q.difficulty === 'Beginner').length, '03'], [t.stats.intermediate, questions.filter((q) => q.difficulty === 'Intermediate').length, '04'], [t.stats.advanced, questions.filter((q) => q.difficulty === 'Advanced').length, '05'], [t.stats.explored, explored.length, '06']];
  const nav = (target) => { setView(target); setSearch(''); setDifficulty('all'); };
  const finishOnboarding = () => { localStorage.setItem('hashquest-onboarded', 'true'); setShowOnboarding(false); };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">H</span><span><strong>HashQuest</strong><small>Your Web3 learning journey</small></span></div><div className="side-label">{t.nav.overview}</div><nav>
      <button className={view === 'overview' ? 'nav-item active' : 'nav-item'} onClick={() => nav('overview')}><span>{icons.overview}</span>{t.nav.overview}</button><button className={view === 'library' ? 'nav-item active' : 'nav-item'} onClick={() => nav('library')}><span>{icons.library}</span>{t.nav.library}</button><button className={view === 'categories' ? 'nav-item active' : 'nav-item'} onClick={() => nav('categories')}><span>{icons.categories}</span>{t.nav.categories}</button><button className={view === 'favorites' ? 'nav-item active' : 'nav-item'} onClick={() => nav('favorites')}><span>{icons.favorites}</span>{t.nav.favorites}<em>{favorites.length}</em></button>
    </nav><div className="sidebar-foot"><div className="progress-caption"><span>{t.stats.explored}</span><strong>{Math.round((explored.length / questions.length) * 100)}%</strong></div><div className="progress"><i style={{ width: `${(explored.length / questions.length) * 100}%` }} /></div><p>{explored.length} / {questions.length} {t.history}</p></div></aside>
    <main className="main-content"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">H</span><strong>HashQuest</strong></div><div className="top-actions"><label className="language"><span>◎</span><select value={language} onChange={(event) => setLanguage(event.target.value)} aria-label={t.language}><option value="en">English</option><option value="fr">Français</option><option value="ar">العربية</option></select></label><button className="avatar" aria-label="Profile">AQ</button></div></header>
      {view === 'overview' && <Overview t={t} stats={stats} current={current} language={language} favorite={favorites.includes(current.id)} onFavorite={() => toggleFavorite(current.id)} onCopy={() => copyQuestion(current)} copied={copied} onNext={nextQuestion} onAsk={() => window.open('https://www.4hacks.io/hashcare', '_blank', 'noopener,noreferrer')} onExplore={() => nav('library')} categories={categories} onCategory={() => nav('categories')} />}
      {view === 'categories' && <Categories t={t} categories={categories} questions={questions} language={language} onSelect={(name) => { setView('library'); setDifficulty('all'); setSearch(name); }} />}
      {(view === 'library' || view === 'favorites') && <Library t={t} view={view} questions={filteredQuestions} language={language} search={search} setSearch={setSearch} difficulty={difficulty} setDifficulty={setDifficulty} favorites={favorites} onFavorite={toggleFavorite} onSelect={selectQuestion} onCopy={copyQuestion} onAsk={() => window.open('https://www.4hacks.io/hashcare', '_blank', 'noopener,noreferrer')} copied={copied} />}
    </main>{showOnboarding && <div className="modal-backdrop"><section className="onboarding"><span className="modal-kicker">{t.step} 01 / 03</span><h2>{t.onboardingTitle}</h2><p>{t.onboardingText}</p><div className="onboarding-steps"><div><b>01</b><span>{t.nav.categories}</span></div><div><b>02</b><span>{t.nav.library}</span></div><div><b>03</b><span>{t.ask}</span></div></div><button className="primary-button" onClick={finishOnboarding}>{t.start} <span>{icons.arrow}</span></button><button className="text-button" onClick={finishOnboarding}>{t.close}</button></section></div>}
  </div>;
}

function Overview({ t, stats, current, language, favorite, onFavorite, onCopy, copied, onNext, onAsk, onExplore, categories, onCategory }) { return <div className="page"><section className="hero"><div className="hero-copy"><span className="eyebrow"><i /> {t.eyebrow}</span><h1>{t.welcome}</h1><p>{t.intro}</p><div className="hero-actions"><button className="primary-button" onClick={onExplore}>{t.explore} <span>{icons.arrow}</span></button><button className="secondary-button" onClick={onNext}>{icons.spark} {t.random}</button></div></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><span>H</span><small>DLT / WEB3</small></div><div className="orbit-label label-one">CONSENSUS</div><div className="orbit-label label-two">BUILD</div></div></section><section className="stats-grid">{stats.map(([label, value, number]) => <div className="stat" key={label}><span className="stat-number">{number}</span><strong>{value}</strong><small>{label}</small></div>)}</section><section className="section-head"><div><span className="eyebrow">{t.featured}</span><h2>{t.questionOf}</h2></div><button className="link-button" onClick={onExplore}>{t.openLibrary} {icons.arrow}</button></section><QuestionCard item={current} t={t} language={language} favorite={favorite} onFavorite={onFavorite} onCopy={onCopy} copied={copied} onNext={onNext} onAsk={onAsk} /><section className="section-head categories-heading"><div><span className="eyebrow">{t.categoriesTitle}</span><h2>{t.categoriesText}</h2></div><button className="link-button" onClick={onCategory}>{t.nav.categories} {icons.arrow}</button></section><div className="mini-categories">{categories.slice(0, 3).map((category, index) => <button key={category} onClick={onCategory}><span>0{index + 1}</span><strong>{category}</strong><i>{icons.arrow}</i></button>)}</div></div>; }

function QuestionCard({ item, t, language, favorite, onFavorite, onCopy, copied, onNext, onAsk }) { return <article className="question-card"><div className="question-meta"><span className="category-pill">{item.category[language]}</span><span className={`difficulty ${item.difficulty.toLowerCase()}`}>{t.difficulty[item.difficulty]}</span><button className={favorite ? 'save-button is-saved' : 'save-button'} onClick={onFavorite}>{favorite ? '♥' : '♡'} <span>{favorite ? t.saved : t.save}</span></button></div><div className="question-body"><span className="question-type">{t.types[item.type] || item.type}</span><h3>{item.question[language]}</h3><div className="tags">{item.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div></div><div className="question-footer"><button className="secondary-button" onClick={() => onCopy(item)}>{icons.copy} {copied ? t.copied : t.copy}</button><button className="ask-button" onClick={onAsk}>{t.ask} <span>{icons.arrow}</span></button><button className="next-button" onClick={onNext}>{t.next} <span>{icons.arrow}</span></button></div></article>; }

function Library({ t, view, questions: list, language, search, setSearch, difficulty, setDifficulty, favorites, onFavorite, onSelect }) { return <div className="page"><section className="page-intro"><span className="eyebrow">{view === 'favorites' ? t.favoritesTitle : t.libraryTitle}</span><h1>{view === 'favorites' ? t.favoritesText : t.libraryText}</h1></section><div className="library-toolbar"><div className="search-box"><span>{icons.library}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t.search} /></div><div className="filter-pills"><button className={difficulty === 'all' ? 'selected' : ''} onClick={() => setDifficulty('all')}>{t.all}</button>{['Beginner', 'Intermediate', 'Advanced'].map((level) => <button key={level} className={difficulty === level ? 'selected' : ''} onClick={() => setDifficulty(level)}>{t.difficulty[level]}</button>)}</div></div><div className="question-list">{list.map((item) => <div className="list-row" key={item.id} onClick={() => onSelect(item.id)}><div className="list-index">{String(item.id).padStart(2, '0')}</div><div className="list-main"><span>{item.category[language]}</span><h3>{item.question[language]}</h3><div className="list-tags">{item.tags.slice(0, 3).map((tag) => <small key={tag}>#{tag}</small>)}</div></div><span className={`difficulty ${item.difficulty.toLowerCase()}`}>{t.difficulty[item.difficulty]}</span><button className={favorites.includes(item.id) ? 'row-save saved' : 'row-save'} onClick={(event) => { event.stopPropagation(); onFavorite(item.id); }}>{favorites.includes(item.id) ? '♥' : '♡'}</button></div>)}</div>{!list.length && <div className="empty-state"><span>{icons.spark}</span><p>{t.noResults}</p></div>}</div>; }

function Categories({ t, categories, questions, language, onSelect }) { return <div className="page"><section className="page-intro"><span className="eyebrow">{t.categoriesTitle}</span><h1>{t.categoriesText}</h1></section><div className="category-grid">{categories.map((category, index) => { const count = questions.filter((item) => item.category[language] === category).length; return <button className="category-card" key={category} onClick={() => onSelect(category)}><span className="category-number">0{index + 1}</span><div className="category-icon">{['◌', '⌁', '◇', '⊙'][index % 4]}</div><h3>{category}</h3><p>{count} {t.questions}</p><span className="category-explore">{t.exploreCategory} {icons.arrow}</span></button>; })}</div></div>; }
export default App;
